language: go

go:
  - "1.12.x"
  - "1.13.x"

gobuild_args: "-v -tags ci"

before_script:
  - NO_VENDOR=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get fyne.io/fyne

script:
  - test -z "$(gofmt -s -e -d $NO_VENDOR | tee /dev/stderr)"
  - go test -tags ci -race -covermode=atomic -coverprofile=coverage.out ./...
  - go vet -tags ci ./...
  - golint -set_exit_status $(go list -tags ci)
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit; fi'
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  global:
          secure: "Col4PBV58xawmhYKqrFuN+uX+v7RjyEsiWzY9xf9RJb3qYeNrnRCtWei1UhJkGXqv/oenF4ul2HqItr+LeTZMMN+aNgFizpX0fwbY4SRVH87+capupvpPbeXzJ2BSP12LPacyjvm4eguf4dRwdND+1h+fNwycPao2RfhVHgJE3C9+w1tYZNw5SpPNCmb1ErJQvIexL+G+AHFkpJ1ZZLUbEWtCJkMyoF8K1IcG4Y/t19kBzg4LLL701RKV1+549Cj/D5jdtfdnYWYjUgutc1LJYVq9YHxoqEhndxuPYYLqiGLAyLYvvuzfbRPZ/Mucv/gLcngRHzH91B547yGJDEHTZSG5571RQtyrr+IoViJsqft05Cv3t4HBRvYTTkTra3AujKlnCeaHz42gI+Mz1OnLHOl4xPTh+3dWGEYu0MkSYu7xH5eEkgJ8LZd8RHxzYNyHOmCynIMdErrgjJ2a6g9ALKmonGSAFuf8STFQX2qBs7M8yFonA7EZxHCZwI+3FAKutUmkrhoZOa6xO6HbpHClLvqG/iSUN29q03GBgyZuf8SzUKLbiN6u+eJChGB9/pHiJQLrCRyiGNw1Pt6xpCQx7hqCl7xCP6BPUPjiwwScYx7Prdi89cXsYz4hnlNlObC+lhBpV/60aCNFvDjs+eceoRk6VcXgZVvQ4Sh08OiaLs="
